# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.2.0.schema.json

PackageIdentifier: Rouchant.Zenit
PackageVersion: 1.2.8
DefaultLocale: es-ES
ManifestType: version
ManifestVersion: 1.2.0
