# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Rouchant.Zenit
PackageVersion: 1.0.3
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Rouchant/Zenit-Tauri/releases/download/1.0.3/Zenit_1.0.3_x64-setup.exe
  InstallerSha256: 77ADCEBE3E620D1186F379A69A195B01C1C217E98AC811D92AF4DDB24C41A2E7
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-04-14
